### ISSUE TITLE
Extract all data-x's into functions that can be called independently 

### ISSUE THREAD

**Issue by AlexMeah** [HFE/boilerplate#13]

**Comment by mikefosbrook** [comment]
Not applied this to all data-x's, However have fixed this for uses of data-slide. 
This was partially written - only realised what this bug was after trying to apply data-slide="next", data-slide="prev" and data-slide="n" (n being a number). Have fixed this so it works. Scrollend callback wasn't firing, which meant the page moved to position but didn't fire tracking or update the indicator.
